### ISSUE TITLE
[Question] Verify authenticity of submitted missing person records

### ISSUE THREAD

**Issue by Frost-Codes** [mutheujoy/MISSING-PERSONS-DATABASE-2024-KENYA-FINANCE-BILL-PROTESTS-#3]
How can we verify that a submitted record is authentic, like that person is actually missing, because people might decide to flood the db with fake submissions ( from the source code every submitted record is saved and displayed)

**Comment by Peter1-cloud** [comment]
Let the names come in.

**Comment by adhiamboperes** [comment]
My opinion is that we let the public verify the information. It doesn't get more open source than that.

**Comment by Frost-Codes** [comment]
> My opinion is that we let the public verify the information. It doesn't get more open source than that.

Imo that would not be the right approch. Its like telling people the information displayed on the site is not authentic, its up to you to figure out if its True. The reason I raised the issue is the so called paid goons might decide to submit illegitimate records and if information of fake records being displayed on the site gets into the public dormain it will ruin the credetability of the whole project

**Comment by Mtsumi** [comment]
Can we verify with police records? We need someone to verify they have been reported missing with the police as well. And their families

**Comment by apexDev37** [comment]
Hey @Joymutheu-dev, this seems like an entire feature in itself. I propose this issue be closed and moved into a [discussion](https://docs.github.com/en/discussions)🌍💬

**Comment by Joymutheu-dev** [comment]
> How can we verify that a submitted record is authentic, like that person is actually missing, because people might decide to flood the db with fake submissions ( from the source code every submitted record is saved and displayed)

To verify the authenticity of submitted records in the missing persons database and mitigate the risk of fake submissions, we will implement the following measures:

1. We will implement a verification process that requires additional validation before a record is made public. This will include:

Contacting the person who submitted the record to verify the information.
Requiring multiple reports or confirmations from different sources for the same missing person. 

2. Document Uploads: Ask for supporting documents that can help verify the identity and missing status of the individual, such as: Recent photographs, ID scans, or social media profiles.
Police reports or missing person reports filed with authorities.

3. Manual Moderation: Assign a team of moderators to review each submission. This team can cross-check the information with official sources or news reports. Community Reporting: Allow the community to report suspicious or incorrect entries. Users can flag records that appear to be fake, which can then be reviewed by moderators.

4. We will Collaborate with law enforcement and government agencies to cross-verify reported missing persons. This partnership can help ensure that only legitimate cases are included.

5. We will also implement automated checks for inconsistencies or duplicates. For example, the system can alert moderators if the same person is reported multiple times under different names.

**Comment by Joymutheu-dev** [comment]
> Let the names come in. 

Sawa, were still working on the backend

**Comment by Joymutheu-dev** [comment]
> My opinion is that we let the public verify the information. It doesn't get more open source than that.

Perfect

**Comment by Joymutheu-dev** [comment]
> Hey @Joymutheu-dev, this seems like an entire feature in itself. I propose this issue be closed and moved into a [discussion](https://docs.github.com/en/discussions)🌍💬

Sawa

**Comment by limo39** [comment]
> > How can we verify that a submitted record is authentic, like that person is actually missing, because people might decide to flood the db with fake submissions ( from the source code every submitted record is saved and displayed)
> 
> To verify the authenticity of submitted records in the missing persons database and mitigate the risk of fake submissions, we will implement the following measures:
> 
> 1. We will implement a verification process that requires additional validation before a record is made public. This will include:
> 
> Contacting the person who submitted the record to verify the information. Requiring multiple reports or confirmations from different sources for the same missing person.
> 
> 2. Document Uploads: Ask for supporting documents that can help verify the identity and missing status of the individual, such as: Recent photographs, ID scans, or social media profiles.
>    Police reports or missing person reports filed with authorities.
> 3. Manual Moderation: Assign a team of moderators to review each submission. This team can cross-check the information with official sources or news reports. Community Reporting: Allow the community to report suspicious or incorrect entries. Users can flag records that appear to be fake, which can then be reviewed by moderators.
> 4. We will Collaborate with law enforcement and government agencies to cross-verify reported missing persons. This partnership can help ensure that only legitimate cases are included.
> 5. We will also implement automated checks for inconsistencies or duplicates. For example, the system can alert moderators if the same person is reported multiple times under different names.
