### ISSUE TITLE
ISSUES WITH THE GIT PULL REQUESTS AND THE REPOSITORY ITSELF

### ISSUE THREAD

**Issue by hackhubafrica** [mutheujoy/MISSING-PERSONS-DATABASE-2024-KENYA-FINANCE-BILL-PROTESTS-#9]
I'm unable to create a pull request because the branches have entirely different commit histories. The error message says, "There isn’t anything to compare. Joymutheu-dev:main and hackhubafrica:master are entirely different commit histories."

**Comment by hackhubafrica** [comment]
![Screenshot_19](https://github.com/user-attachments/assets/4781e47b-8b3e-4d25-91ad-1ad0e12a6d47)

**Comment by hassankirwa** [comment]
I have had the same issues myself but i have requested to make a branch

**Comment by Mtsumi** [comment]
Did you fork the repo @hassankirwa

**Comment by hassankirwa** [comment]
> Did you fork the repo @hassankirwa

Yes i was able to but it wasnt running locally eithe so what i did i restructured the files afresh and rebuilt there,
i will be pushing the changes on branch1 i created above ..i will include a markdown explaining the code then after that it will be merged to main repo

**Comment by hassankirwa** [comment]
Below are steps of how i manouvered the issue of clonning the repo to local machine 
1. I first clonned the repo with git clone command and i met the error below
![git-error](https://github.com/user-attachments/assets/baa3da4c-c460-49aa-bbd1-a8af4af692e9)
2. I Ran git reset
![git-error2](https://github.com/user-attachments/assets/83e43ad5-00b4-45db-8d75-cd36cc232752)
3. Ran git config core.protectNTFS false
4. Ran git checkout (just git checkout, no * at the end of command).
![error3](https://github.com/user-attachments/assets/bba633c0-0855-4a96-854c-09e4cd8586a2)
5. Ran git status

**Comment by hassankirwa** [comment]
@Mtsumi @hackhubafrica Hope the above will be helpful

**Comment by hassankirwa** [comment]
> Did you fork the repo @hassankirwa

I cloned it

**Comment by Mtsumi** [comment]
You have to fork first and then clone your forked repository. You can make changes in a new branch, then push and create a PR, it will automatically make a pr to the repo as well.

**Comment by hassankirwa** [comment]
True..also if not mentioned and face the above mentioned errors the process is still the same

**Comment by Dovineowuor** [comment]
Fam we need to work on separate forks then pull and meet to merge to avoid this masquerading these kinds of conflicts

**Comment by apexDev37** [comment]
These are valid claims!
Docs to guide users will be added soon (ie. `CONTRIBUTORS.md`, etc) to streamline the contributor process and experience🌍

**Comment by Dovineowuor** [comment]
Working from your fork makes it easy to work and on creating a pull request this directs this to the main branch of the parent repository which i propose we have a common time to have all the conflicts parse resolved prior to merging. #Aluta

**Comment by Dovineowuor** [comment]
Lets have a time and make it fast

**Comment by Joymutheu-dev** [comment]
> Fam we need to work on separate forks then pull and meet to merge to avoid this masquerading these kinds of conflicts

Nice

**Comment by Dovineowuor** [comment]
I will be pushing the working version of the form and the index page so that we may get going from there. In the meantime, is there anyone who have sorted it out?
Keep me posted

**Comment by hassankirwa** [comment]
> I will be pushing the working version of the form and the index page so that we may get going from there. In the meantime, is there anyone who have sorted it out? Keep me posted

Some changes on branch one had beed pushed yesterday if you can run it locally and see where you can update on forms etc 
had work on some parts including home page

**Comment by hassankirwa** [comment]
Also team its my wish before we merge to main or one of these coming days we have a forum be it a space or google meet we discuss on the way forward and be on the same page
I am also informed there are other teams doing the same project i wish later on we could all converge in one place and do other more and more open source projects

**Comment by Dovineowuor** [comment]
> > I will be pushing the working version of the form and the index page so that we may get going from there. In the meantime, is there anyone who have sorted it out? Keep me posted
> 
> Some changes on branch one had beed pushed yesterday if you can run it locally and see where you can update on forms etc had work on some parts including home page

I will review them then merge them to the main branch tommorow

**Comment by Dovineowuor** [comment]
> Also team its my wish before we merge to main or one of these coming days we have a forum be it a space or google meet we discuss on the way forward and be on the same page I am also informed there are other teams doing the same project i wish later on we could all converge in one place and do other more and more open source projects

Exactly my point. We need to have this frequently for ice-breaking and progress logging
